Ace 265 contacto
ace-software-dev/Landing-Page-SMA pull request #14
Opened 2024-01-19 00:14 UTC by pau-cardoso

## Cómo correr
1. Asegurarse de tener una versión de node superior a la 18.0.0. Se pueden apoyar con la librería nvm
2. Instalar las dependencias en la terminal con `npm i`
3. Correr el servidor localmente con el comando `npm run dev`

- [ ] Diseño responsivo para todos los dispositivos
- [ ] Colores correctos
- [ ] Textos y campos correctos

| Mobile | Tablet | Desktop |
|--|--|--|
| <img width="320" alt="image" src="https://github.com/ace-software-dev/Landing-Page-SMA/assets/70352297/f553ca7e-bc24-4fdc-870e-b1056dc62df2"> | <img width="764" alt="image" src="https://github.com/ace-software-dev/Landing-Page-SMA/assets/70352297/20c55d3c-43f1-4242-996f-7452f85d9a1b"> | <img width="1506" alt="image" src="https://github.com/ace-software-dev/Landing-Page-SMA/assets/70352297/16b76367-5a8a-4c2a-9e2a-d319a3a98086"> |

2024-01-19 06:39 UTC, FelipeYepez requested changes

2024-01-19 06:39 UTC, FelipeYepez commented on src/app/components/molecules/ContactForm/contact-form.tsx
> +      </div>
Se podría cambiar texto a "Estoy interesado" o el de Figma "Quiero invertir"

2024-01-19 06:39 UTC, FelipeYepez commented on src/app/components/molecules/ContactForm/contact-form.tsx
> +        </div>
A esto se va a agregar un Aviso de Privacidad como link?

2024-01-19 06:39 UTC, FelipeYepez commented on src/app/components/molecules/ContactForm/contact-form.tsx
> +        <div className="flex items-center gap-3">
Evaluar gap responsivo incluido en nuevo commit.

2024-01-19 06:39 UTC, FelipeYepez commented on src/app/components/molecules/ContactInformation/contact-information.tsx
> +        <div className="text-xl font-bold">Información de Contacto</div>
Letra en general, íconos y padding del componente entero puede aumentar para dispositivos grandes ya que se ve más pequeño que en Figma cuando el tamaño de pantalla aumenta.

2024-01-19 06:39 UTC, FelipeYepez commented on src/app/components/molecules/InputField/input-field.tsx
> +  error,
Prop error no está siendo usado

2024-01-19 16:06 UTC, pau-cardoso commented on src/app/components/molecules/ContactForm/contact-form.tsx
> +        </div>
Yo supongo que si pero aún no tengo ningún link a qué documento sería. Ya dejé el Link preparado para poner solo la ruta cuando lo tengamos tho.

2024-01-23 05:05 UTC, FelipeYepez approved these changes
LGTM

2024-01-23 05:05 UTC, merged